# Generated by Django 4.1.6 on 2023-02-10 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
