# Generated by Django 4.1.6 on 2023-02-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_customuser_is_teacher_alter_customuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
